### PR TITLE
Add support for Ollama, Palm, Claude-2, Cohere, Replicate Llama2 CodeLlama (100+LLMs) - using LiteLLM

### PR DESCRIPTION
**Pull request by ishaan-jaff**
This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM is a lightweight package to simplify LLM API calls - use any llm as a drop in replacement for gpt-3.5-turbo. 

Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
@jackmpcollins noticed you support function calling, we support function calling for OpenAI models 

As for Non OpenAI models we don't support function calling but some repos using us with prompt hacking, example: https://github.com/KillianLucas/open-interpreter

**Comment by jackmpcollins** [comment]
Thanks for the PR @ishaan-jaff LiteLLM is exactly what I was hoping for to expand magentic to support more LLMs. However I will hold off on merging until I have done some more thinking about how I want to support different backends, and also how to deal with models that don't support function calling - which is required for most of magentic's features.

Have you any plans to add support for the function calling API to models by using prompts within LiteLLM? Or is LiteLLM going to remain free of prompt engineering?

**Comment by ishaan-jaff** [comment]
@jackmpcollins that's awesome

> Have you any plans to add support for the function calling API to models by using prompts within LiteLLM? Or is LiteLLM going to remain free of prompt engineering?

we're definitely not going to be doing any prompt engineering on LiteLLM

Our current behavior for Non OpenAI LLMs is - If a user passes in function calling for claude2 - litellm raises an exception (since we would not actually pass in the function)

**Comment by jackmpcollins** [comment]
LiteLLM backend added in PR https://github.com/jackmpcollins/magentic/pull/54 and released in https://github.com/jackmpcollins/magentic/releases/tag/v0.9.0

**Pull request closed without merging**
